<Project Sdk="Microsoft.NET.Sdk">

	<!-- These define the critical project details. Such as the net version, C# language version, null enable and do not generate assembly info (we need a custom one) -->
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<LangVersion>Latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<PropertyGroup>
		<!-- This should point to wherever your games primary EXE is -->
		<TheLongDarkPath>C:\Program Files (x86)\Steam\steamapps\common\TheLongDark</TheLongDarkPath>
		<ReleaseFolderPath>C:\The Long Dark\Projects\Maintained\AdaptiveArsenal\Test</ReleaseFolderPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <WarningLevel>6</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <WarningLevel>6</WarningLevel>
	</PropertyGroup>

	<!-- List of used references -->
	<ItemGroup>
		<PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.36.0" />
		<PackageReference Include="STBlade.Modding.TLD.LocalizationUtilities" Version="2.0.0" />
		<PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
	</ItemGroup>

	<!-- Most commonly used using's. Add to this so you dont need to define them in the cs files -->
	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="WeaponSkins\FlareGun\FlareGun_Yellow.png" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="WeaponSkins\FlareGun\Blue.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Blue.png" />
	  <None Remove="WeaponSkins\FlareGun\Green.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Green.png" />
	  <None Remove="WeaponSkins\FlareGun\Red.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Red.png" />
	  <None Remove="WeaponSkins\FlareGun\Icons\Blue.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Icons\Blue.png" />
	  <None Remove="WeaponSkins\FlareGun\Icons\Green.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Icons\Green.png" />
	  <None Remove="WeaponSkins\FlareGun\Icons\Red.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Icons\Red.png" />
	  <None Remove="WeaponSkins\FlareGun\Icons\Yellow.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Icons\Yellow.png" />
	  <None Remove="WeaponSkins\FlareGun\Yellow.png" />
	  <EmbeddedResource Include="WeaponSkins\FlareGun\Yellow.png" />
	  <None Remove="WeaponSkins\Rifle\Noir.png" />
	  <EmbeddedResource Include="WeaponSkins\Rifle\Noir.png" />
	  <None Remove="WeaponSkins\Rifle\Olive.png" />
	  <EmbeddedResource Include="WeaponSkins\Rifle\Olive.png" />
	  <None Remove="WeaponSkins\Rifle\Red.png" />
	  <EmbeddedResource Include="WeaponSkins\Rifle\Red.png" />
	  <None Remove="WeaponSkins\Revolver\Brown.png" />
	  <EmbeddedResource Include="WeaponSkins\Revolver\Brown.png" />
	  <None Remove="WeaponSkins\Revolver\Orange.png" />
	  <EmbeddedResource Include="WeaponSkins\Revolver\Orange.png" />
	  <None Remove="WeaponSkins\Revolver\Red.png" />
	  <EmbeddedResource Include="WeaponSkins\Revolver\Red.png" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="WeaponSkins\Revolver\Icons\" />
	  <Folder Include="WeaponSkins\Rifle\Icons\" />
	</ItemGroup>

	<!-- This is a build event. It will copy your dll to the currently defined TheLongDarkPath's Mods folder -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- This copies the mods files to the games mod dir -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)/Mods" />
		<!-- This copies the mods files to a designated release folder. Speeds up finding the dll after a build -->
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ReleaseFolderPath)" />
	</Target>
</Project>
